### ISSUE TITLE
How do these images appear to search engines?

### ISSUE THREAD

**Issue by mikelittle** [humanmade/Gaussholder#10]
The reason I ask is, by coincidence, the day after I read your blog post on hmn.md, I came accross this search for similar images result on Google https://www.google.com/search?sa=N&biw=1440&bih=801&tbs=simg:CAESvAEauQELELCMpwganAEKOggCEhSqGZcYkBjrDLMejRiOGNgesw7qDhogZOo_1J4aBzyejRSsOzJkRBKzjW-7OfF4gvgSPBj0M9LcKXggDEiicD50PxRm0D5QP1BmuD68Pgg-CBfYsoTqKOuss9SyJOrst6SyiOtMtGjAuE6JePZruh7mYHNGLLvMfPe2HMB9BmLjJFHrxIhFlvy4jRkfcrdDYaFz-sgPaUzsMCxCOrv4IGgoKCAgBEgQOCu0UDA&tbm=isch&ved=0ahUKEwiqj5eX_5_LAhWGfxoKHWSTDowQsw4IQA#imgrc=_
![google_search](https://cloud.githubusercontent.com/assets/358499/13435663/3d9562bc-dfd3-11e5-83bd-42589a380e8a.png)

As far as I can see, they are all results from Google Plus pages. I Guess google plus uses the same or similar technique. Going to the pages, them selves shows me normal images. If they are lazy loading it is quicker than I can see.

**Comment by rmccue** [comment]
The `src` for all the images is set by default to a blank 1x1 GIF using an inline data: URI, so shouldn't appear in search results. That said, neither will the real images appear, I believe.
