### ISSUE TITLE
Errors with special characters in file names

### ISSUE THREAD

**Issue by swissspidy** [humanmade/Gaussholder#17]
On a site there's an attachment with some umlauts in it. Running `wp gaussholder process` for that image causes a fatal error:

```sh
Fatal error: Uncaught exception 'ImagickException' with message 'unable to open image `<filename>': No such file or directory @ error/blob.c/OpenBlob/2641' in <path>/gaussholder/inc/jpeg/namespace.php:190
```

I'm running PHP 5.6 with ImageMagick 6.7.7-10 2016-06-01 Q16.

`\WP_Image_Editor_Imagick::load()` wraps the Imagick calls in a `try { … } catch ( $e ) { return new WP_Error( 'invalid_image', $e->getMessage(), … ); }` block, and I think so should Gaussholder.

**Comment by rmccue** [comment]
Better than catching the error, can we prevent it? Is there any way to encode the filename that Imagick will be able to open it?

**Comment by swissspidy** [comment]
It seems like I cannot reproduce it right now, but I'll keep an eye on it. Perhaps the file name wasn't in the expected normalization form.

I agree that error prevention would be great, although any exceptions should really be caught there.

**Comment by rmccue** [comment]
Feel free to reopen if you spot this again.
