### ISSUE TITLE
Support placeholders for all attachments

### ISSUE THREAD

**Issue by swissspidy** [humanmade/Gaussholder#18]
Currently, the plugin only scans through the post content to apply the placeholder. It would be way more useful if it could filter `wp_get_attachment_image_attributes` instead so it applies to all places where attachments are being used.

I've done this on a site in a few lines of code and it works quite well. Happy to put together a PR if that sounds like a reasonable addition.

**Comment by rmccue** [comment]
Originally, we were using this, however since this is generated when images are inserted into a post, this inserts a _lot_ of data into posts which cannot easily be regenerated (e.g. if the available image sizes change). Instead, we moved to a display filter.

Happy to re-add support for this, but it needs to be done in such a way that placeholder data isn't saved.

**Comment by swissspidy** [comment]
As far as I can tell, `image_media_send_to_editor()` doesn't use `wp_get_attachment_image()` (where that filter resides). It's used in the image editor though.

I'm using the following code on a site and it works just fine to apply Gaussholder to things like featured images.

```php

/**
 * Applies Gaussholder to all attachments, not just images in the post content.
 *
 * @param array        $attr       Attributes for the image markup.
 * @param \WP_Post     $attachment Image attachment post.
 * @param string|array $size       Requested image size.
 *
 * @return array The modified image attributes.
 */
add_filter( 'wp_get_attachment_image_attributes', function ( $attr, \WP_Post $attachment, $size ) {
	if ( is_admin() || wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) || ! Gaussholder\is_enabled_size( $size ) ) {
		return $attr;
	}

	$attr['data-originalsrc'] = $attr['src'];
	$attr['data-originalsrcset'] = isset( $attr['srcset'] ) ? $attr['srcset'] : '';

	$blank     = file_get_contents( Gaussholder\PLUGIN_DIR . '/assets/blank.gif' );
	$blank_url = 'data:image/gif;base64,' . base64_encode( $blank );

	// Replace src with our blank GIF
	$attr['src'] = esc_attr( $blank_url );

	// Remove srcset
	unset( $attr['srcset'] );

	// Add the actual placeholder
	$placeholder = Gaussholder\get_placeholder( $attachment->ID, $size );
	$attr['data-gaussholder'] = esc_attr( $placeholder );

	// Add final size
	$size_data = Gaussholder\get_size_data( $size );
	$radius = Gaussholder\get_blur_radius_for_size( $size );

	$attr['data-gaussholder-size'] = implode( ',', [
		$size_data['width'],
		$size_data['height'],
		$radius,
	] );

	return $attr;
}, 10, 3 );
```

**Comment by swissspidy** [comment]
In this regard I noticed that regular images inserted in the post content (e.g. using the `[caption]` shortcode) are not being handled.

`mangle_images()` filters `the_content` and handles all images that have the `data-gaussholder-id` attribute, which is added by `add_placeholder_to_attributes()` (hooked to `wp_get_attachment_image_attributes`). As `wp_get_attachment_image()` is used by `gallery_shortcode()`, this should work for galleries. Just not for other images in the editor.

Similarly to `wp_make_content_images_responsive()`, `data-gaussholder-id` attributes need to be added to content images on the fly.

**Comment by swissspidy** [comment]
Actually, forget my last comment… I misread the regex in `mangle_images()`. Turns out the regex is just not 100% correct.

**Comment by rmccue** [comment]
@swissspidy Per #26, does that mean this initial report is invalid, or?

**Comment by swissspidy** [comment]
It's still valid.

`add_placeholder_to_attributes()` hooks into `wp_get_attachment_image_attributes` to add the `data-gaussholder-id` attribute, which `mangle_images()` looks for inside `the_content`.

When I use `the_post_thumbnail()` somewhere else in the theme, nothing happens.
