### ISSUE TITLE
Broken Readme Image

### ISSUE THREAD

**Issue by noeltock** [humanmade/Gaussholder#28]

**Comment by rmccue** [comment]
Weird. The original link (https://giant.gfycat.com/MemorableCoordinatedAngelfish.gif) in the source works fine; must be a problem since the readme hasn't been updated.

Will see if I can flush it out with a dummy cache change.

**Comment by rmccue** [comment]
No dice. Will add to the repo instead.

**Comment by rmccue** [comment]
Fixed in 239878ef10fc2dc998cfc557a952f9ddfe8f2c88.
