### ISSUE TITLE
Skewed images when resizing window

### ISSUE THREAD

**Issue by swissspidy** [humanmade/Gaussholder#29]
In `handleElement()`, Gaussholder sets the image's dimensions using inline style: https://github.com/humanmade/Gaussholder/blob/239878ef10fc2dc998cfc557a952f9ddfe8f2c88/assets/gaussholder.js#L80-L98

This works fairly well. However, on a site we're building we use something like this to have images always take up the full width:

```css
img {
	max-width: 100%;
	height: auto;
}
```

Images are wrapped by a flexible container (e.g. `float: left; width: 33%;`). When resizing the window, the actual width image on the screen changes, while the inline style doesn't.

Proposed solution:

Do not set a specific image height in inline style, and set it to `auto` instead.

**Comment by rmccue** [comment]
The explicit height/width is intentional to avoid causing reflows or jank on the page, and would be hard to change out.

Is there any other way we could handle this?
