### ISSUE TITLE
Tag and release 1.1.4 and 1.1.5

### ISSUE THREAD

**Issue by johnbillion** [humanmade/Gaussholder#70]
I noticed an issue with Gaussholder but it's already been fixed in 1.1.5, but neither this nor 1.1.4 are available via Composer as there's no tag or release in the repo.

**Comment by johnbillion** [comment]
Looks like this is normally done via CircleCI but it's no longer functioning

**Comment by roborourke** [comment]
Thanks @johnbillion, there was a new SSH key for the machine user requiring re-authentication. Fixed in #72

**Comment by roborourke** [comment]
v1.1.6 is now released.
