### ISSUE TITLE
Using with HM WPThumb?

### ISSUE THREAD

**Issue by BoweFrankema** [humanmade/Gaussholder#9]
First off: AWESOME STUFF! 

I'm already using WPThumb heavily across my client projects and I was wondering if Gaussholder can be used in combination with WPThumb?

**Comment by rmccue** [comment]
@BoweFrankema Sorry for the delay! WPThumb should work correctly with Gaussholder, but I can't say for certain. Gaussholder does its own resizing from the original image, and hence doesn't require hard copies of the downsized images.

That said, we no longer maintain WPThumb, so I'd recommend an alternative solution in any case.
